### PR TITLE
feat: generate `.tmTheme` files from VSCode

### PR DESCRIPTION
**Pull request by nekowinston**

### CODE REVIEW

**Comment by nekowinston** [comment]
Still not perfect but should be an improvement over the current state of the repo.

**Comment by spookyintheam** [comment]
This looks good from the first glance and since this is generated from vscode, I don't think this requires much review.

I'll try out the theme files from this branch today and let you know in a day.

**Review by sgoudham — APPROVED** [review]
Files look great, thanks!

**Comment by sgoudham** [comment]
Will test out some other files in the morning regarding different languages ^^

**Review by spookyintheam — APPROVED** [review]

**Pull request merged**
